<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLCP3sb4\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLCP3sb4/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerLCP3sb4.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerLCP3sb4\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerLCP3sb4\appAppKernelProdContainer([
    'container.build_hash' => 'LCP3sb4',
    'container.build_id' => 'be95f97a',
    'container.build_time' => 1722267059,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLCP3sb4');
