<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUUuHnG2\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUUuHnG2/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerUUuHnG2.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerUUuHnG2\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerUUuHnG2\appAppKernelProdContainer([
    'container.build_hash' => 'UUuHnG2',
    'container.build_id' => '3ce8f20c',
    'container.build_time' => 1703156878,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUUuHnG2');
