<?php

# This file was automatically generated by the MediaWiki 1.36.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "MuizenWiki";
$wgMetaNamespace = "MuizenWiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/wiki";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://www.muizenmesh.co.za";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/wiki.gif" ];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "admin@muizenmesh.co.za";
$wgPasswordSender = "admin@muizenmesh.co.za";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "sexthera_mw19627";
$wgDBuser = "sexthera_mw19627";
$wgDBpassword = "@p3i5kS7H@";

# MySQL specific settings
$wgDBprefix = "mwqe_";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE; #Or use CACHE_ACCEL
$wgMemCachedServers = [];
$wgParserCacheType = CACHE_NONE; 
$wgCompressRevisions = true;

##Jobs
$wgJobRunRate = 0.01;

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;
$wgWikiLoveGlobal = true;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale. This should ideally be set to an English
## language locale so that the behaviour of C library functions will
## be consistent with typical installations. Use $wgLanguageCode to
## localise the wiki.
$wgShellLocale = "en_US.utf8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";
#$wgMainCacheType = CACHE_DB

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "cbeeaa7f5aea2cd2967d92abda6a35314a778c03af0d252b2dc0a44bc6081892";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "6ghebnkjlqovmn4v";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

# Enabled Extensions
wfLoadExtension ( 'VisualEditor' );
wfLoadExtension("EmbedVideo");
wfLoadExtension( 'WikiLove' );

### End of automatically generated settings.###
# Add more configuration options below.##


##TEMP DIR & CACHING
$wgTmpDirectory = "/home/sexthera/tmp_gcpiud";
#$wgMainCacheType = CACHE_NONE;
$wgMainCacheType = CACHE_ANYTHING;

#SEMANTICS
#wfLoadExtension( 'SemanticMediaWiki' );
#enableSemantics( 'muizenmesh.co.za/wiki' );

wfLoadExtension( 'Kartographer' );
#$wgKartographerMapServer = 'https://tiles.wmflabs.org';
#$wgKartographerStyles = "hike-bike";
$wgKartographerMapServer = 'https://tile.openstreetmap.fr';
$wgKartographerDfltStyle = 'osmfr';

wfLoadExtension( 'JsonConfig' );
#wfLoadExtension( 'Maps' );
wfLoadExtension( 'InputBox' );

#AbuseFilter
#wfLoadExtension( 'AbuseFilter' );
#wfLoadExtension( 'StopForumSpam' );

#$wgSFSIPListLocation = '/home/sexthera/public_html/muizenmesh.co.za/wiki/deny.txt';
#$wgDebugLogGroups['StopForumSpam'] = '/home/sexthera/public_html/muizenmesh.co.za/wiki/stopforumspam.log';

##CAPTCHA SECTION##
#wfLoadExtensions([ 'ConfirmEdit', 'ConfirmEdit/QuestyCaptcha' ]);

## Add your QuestyCaptchaquestions below:
#$wgCaptchaQuestions = [
#	'What is the name of the Bay near Muizenberg?' => 'False Bay',
#	'What is the name of the ocean' => 'INDIAN OCEAN', // Answers are case insensitive
#	'What is the name of this wiki?' => $wgSitename, // You can use variables
#	'How many fingers does a hand have?' => [ 5, 'five' ], // A question may have many answers
#];


#$wgCaptchaTriggers['edit'] = true;
#$wgCaptchaTriggers['create'] = true;
#$wgCaptchaTriggers['createtalk'] = true;
#$wgCaptchaTriggers['addurl'] = true;
#$wgCaptchaTriggers['createaccount'] = true;
#$wgCaptchaTriggers['badlogin'] = true;

##END CAPTCHA SECION##

# Disable reading by anonymous users
#$wgGroupPermissions['*']['read'] = false;

# Disable anonymous editing
$wgGroupPermissions['*']['edit'] = false;

# Anonymous users can't create pages
$wgGroupPermissions['*']['createpage'] = false;

# Prevent new user registrations except by sysops
$wgGroupPermissions['*']['createaccount'] = false;

#REVOKE ACCOUNT CREATION SET TO FALSE (True will overide ConfirmAccount Extension)
#$wgGroupPermissions['*']['createaccount'] = true;

#INVOKE ACCOUNT CONFIRMATION
wfLoadExtension( 'ConfirmAccount' );
wfLoadExtension( 'UserAgreement' );

$wgMakeUserPageFromBio = false;
$wgAutoWelcomeNewUsers = false;
$wgConfirmAccountRequestFormItems = [
 	'UserName'        => [ 'enabled' => true ],
 	'RealName'        => [ 'enabled' => false ],
 	'Biography'       => [ 'enabled' => false, 'minWords' => 50 ],
 	'AreasOfInterest' => [ 'enabled' => false ],
 	'CV'              => [ 'enabled' => false ],
 	'Notes'           => [ 'enabled' => true ],
 	'Links'           => [ 'enabled' => false ],
 	'TermsOfService'  => [ 'enabled' => false ],
 ];

$wgConfirmAccountContact = 'admin@muizenmesh.co.za';
$wgGroupPermissions['bureaucrat']['confirmaccount-notify'] = true;

#SET SPECIAL PERMISSIONS FOR SYSOP
$wgGroupPermissions['sysop']['deletelogentry'] = true;
$wgGroupPermissions['sysop']['deleterevision'] = true;

#CREATE hidden projectmember group
$wgGroupPermissions['projectmember']['bot'] = true;
$wgGroupPermissions['projectmember']['block'] = true;
$wgGroupPermissions['projectmember']['delete'] = true;

#FOR HARDCORE ABUSERS
## Disable for everyone.
$wgGroupPermissions['*']['edit'] = false;
## Disable for users, too: by default 'user' is allowed to edit, even if '*' is not.
$wgGroupPermissions['user']['edit'] = false;
## Make it so users with confirmed email addresses are in the group.
$wgAutopromote['emailconfirmed'] = APCOND_EMAILCONFIRMED;
## Hide group from user list.
$wgImplicitGroups[] = 'emailconfirmed';
## Finally, set it to true for the desired group.
$wgGroupPermissions['emailconfirmed']['edit'] = true;

## Prevent new user registrations except by sysops
#$wgGroupPermissions['*']['createaccount'] = false;

#$wgDnsBlacklistUrls = array( 'xbl.spamhaus.org.', 'dnsbl.tornevall.org.', 'spam.dnsbl.sorbs.net.', 'rbl.dnsbl.im.', 'noptr.spamrats.com.', 'all.s5h.net.', 'z.mailspike.net.', 'mantaplink.com.);

#DEBUG
#error_reporting( -1 );
#ini_set( 'display_errors', 1 );

#DETAIL DEBUG OPS
#$wgShowExceptionDetails = true;
#$wgShowDBErrorBacktrace = true;
#$wgShowSQLErrors = true;


##POS HACK
ini_set( 'memory_limit', '32M' );
