<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4RD3Cnm\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4RD3Cnm/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4RD3Cnm.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\Container4RD3Cnm\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \Container4RD3Cnm\appAppKernelDevDebugContainer([
    'container.build_hash' => '4RD3Cnm',
    'container.build_id' => 'a1919a8a',
    'container.build_time' => 1694715098,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4RD3Cnm');
